[package]
name = "temp_pro"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-cats = "0.1.3"
# cargo-cats = "0.1.2"