[package]
name = "some"
version = "0.1.0"
edition = "2021"
default-run = "main"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "*"

[[bin]]
name = "sender"
path = "src/sender.rs"
[[bin]]
name = "main"
path = "src/main.rs"