[package]
name = "rust-NN"
version = "0.1.0"
edition = "2021"
default-run="testing2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "*"
rand = "*"

[[bin]]
name = "testing2"
path = "src/testing2.rs"
