[package]
name = "hello_torch_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tch = "0.19.0"


# [dependencies]
# tch = {version="0.17.0", path="tch-rs"}

# [dev-dependencies]
# torch-sys = {version="0.17.0", path="tch-rs/torch-sys"}


# [build-dependencies]
# pkg-config = "0.3.32"