pub use wasm_bindgen::prelude::*;

#[path = "js_fn.rs"]
pub mod js_fn;
pub use js_fn::*;
#[path = "console.rs"]
pub mod console;
pub use console::*;
#[path = "add.rs"]
pub mod add;
pub use add::*;
#[path = "closures.rs"]
pub mod closures;
pub use closures::*;
#[path = "dom.rs"]
pub mod dom;
pub use dom::*;
#[path = "duck_typed_interfaces.rs"]
pub mod duck_typed_interfaces;
pub use duck_typed_interfaces::*;
#[path = "fetch.rs"]
pub mod fetch;
pub use fetch::*;
#[path = "julia_set.rs"]
pub mod julia_set;
pub use julia_set::*;
#[path = "counter.rs"]
pub mod counter;
pub use counter::*;
#[path = "paint.rs"]
pub mod paint;
pub use paint::*;
#[path = "performance.rs"]
pub mod performance;
pub use performance::*;
#[path = "canvas.rs"]
pub mod canvas;
pub use canvas::*;
#[path = "request_animation_frame.rs"]
pub mod request_animation_frame;
pub use request_animation_frame::*;
#[path = "wasm_wasm.rs"]
pub mod wasm_wasm;
pub use wasm_wasm::*;
#[path = "wasm_wasm_imports.rs"]
pub mod wasm_wasm_imports;
pub use wasm_wasm_imports::*;
#[path = "weather.rs"]
pub mod weather;
pub use weather::*;
#[path = "web_audio.rs"]
pub mod web_audio;
pub use web_audio::*;
#[path = "webgl.rs"]
pub mod webgl;
pub use webgl::*;
#[path = "webrtc.rs"]
pub mod webrtc;
pub use webrtc::*;
#[path = "websockets.rs"]
pub mod websockets;
pub use websockets::*;
