[package]
name = "dict"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro= true
# name = "lib"
# path = "src/lib.rs"

[dependencies]
# num-traits = "*"