_planks": "Dzsungelfa deszka",
    "block.minecraft.jungle_pressure_plate": "Dzsungelfa nyom\u00f3lap",
    "block.minecraft.jungle_sapling": "Dzsungelfacsemete",
    "block.minecraft.jungle_slab": "Dzsungelfa lap",
    "block.minecraft.jungle_stairs": "Dzsungelfa l\u00e9pcs\u0151",
    "block.minecraft.jungle_trapdoor": "Dzsungelfa csap\u00f3ajt\u00f3",
    "block.minecraft.jungle_wood": "Dzsungelfablokk",
    "block.minecraft.kelp": "H\u00edn\u00e1r",
    "block.minecraft.kelp_plant": "H\u00edn\u00e1rsz\u00e1r",
    "block.minecraft.ladder": "L\u00e9tra",
    "block.minecraft.lapis_block": "Lazuritblokk",
    "block.minecraft.lapis_ore": "Lazurit\u00e9rc",
    "block.minecraft.large_fern": "Nagy p\u00e1fr\u00e1ny",
    "block.minecraft.lava": "L\u00e1va",
    "block.minecraft.lever": "Kar",
    "block.minecraft.light_blue_banner": "Vil\u00e1gosk\u00e9k z\u00e1szl\u00f3",
    "block.minecraft.light_blue_bed": "Vil\u00e1gosk\u00e9k \u00e1gy",
    "block.minecraft.light_blue_carpet": "Vil\u00e1gosk\u00e9k sz\u0151nyeg",
    "block.minecraft.light_blue_concrete": "Vil\u00e1gosk\u00e9k beton",
    "block.minecraft.light_blue_concrete_powder": "Vil\u00e1gosk\u00e9k sz\u00e1razbeton",
    "block.minecraft.light_blue_glazed_terracotta": "Vil\u00e1gosk\u00e9k m\u00e1zas ker\u00e1mia",
    "block.minecraft.light_blue_shulker_box": "Vil\u00e1gosk\u00e9k shulkerdoboz",
    "block.minecraft.light_blue_stained_glass": "Vil\u00e1gosk\u00e9k festett \u00fcveg",
    "block.minecraft.light_blue_stained_glass_pane": "Vil\u00e1gosk\u00e9k festett \u00fcveglap",
    "block.minecraft.light_blue_terracotta": "Vil\u00e1gosk\u00e9k terrakotta",
    "block.minecraft.light_blue_wool": "Vil\u00e1gosk\u00e9k gyapj\u00fa",
    "block.minecraft.light_gray_banner": "Vil\u00e1gossz\u00fcrke z\u00e1szl\u00f3",
    "block.minecraft.light_gray_bed": "Vil\u00e1gossz\u00fcrke \u00e1gy",
    "block.minecraft.light_gray_carpet": "Vil\u00e1gossz\u00fcrke sz\u0151nyeg",
    "block.minecraft.light_gray_concrete": "Vil\u00e1gossz\u00fcrke beton",
    "block.minecraft.light_gray_concrete_powder": "Vil\u00e1gossz\u00fcrke sz\u00e1razbeton",
    "block.minecraft.light_gray_glazed_terracotta": "Vil\u00e1gossz\u00fcrke m\u00e1zas ker\u00e1mia",
    "block.minecraft.light_gray_shulker_box": "Vil\u00e1gossz\u00fcrke shulkerdoboz",
    "block.minecraft.light_gray_stained_glass": "Vil\u00e1gossz\u00fcrke festett \u00fcveg",
    "block.minecraft.light_gray_stained_glass_pane": "Vil\u00e1gossz\u00fcrke festett \u00fcveglap",
    "block.minecraft.light_gray_terracotta": "Vil\u00e1gossz\u00fcrke terrakotta",
    "block.minecraft.light_gray_wool": "Vil\u00e1gossz\u00fcrke gyapj\u00fa",
    "block.minecraft.light_weighted_pressure_plate": "K\u00f6nny\u0171 s\u00falym\u00e9r\u0151 nyom\u00f3lap",
    "block.minecraft.lilac": "Orgona",
    "block.minecraft.lily_pad": "Tavir\u00f3zsa",
    "block.minecraft.lime_banner": "Vil\u00e1gosz\u00f6ld z\u00e1szl\u00f3",
    "block.minecraft.lime_bed": "Vil\u00e1gosz\u00f6ld \u00e1gy",
    "block.minecraft.lime_carpet": "Vil\u00e1gosz\u00f6ld sz\u0151nyeg",
    "block.minecraft.lime_concrete": "Vil\u00e1gosz\u00f6ld beton",
    "block.minecraft.lime_concrete_powder": "Vil\u00e1gosz\u00f6ld sz\u00e1razbeton",
    "block.minecraft.lime_glazed_terracotta": "Vil\u00e1gosz\u00f6ld m\u00e1zas ker\u00e1mia",
    "block.minecraft.lime_shulker_box": "Vil\u00e1gosz\u00f6ld shulkerdoboz",
    "block.minecraft.lime_stained_glass": "Vil\u00e1gosz\u00f6ld festett \u00fcveg",
    "block.minecraft.lime_stained_glass_pane": "Vil\u00e1gosz\u00f6ld festett \u00fcveglap",
    "block.minecraft.lime_terracotta": "Vil\u00e1gosz\u00f6ld terrakotta",
    "block.minecraft.lime_wool": "Vil\u00e1gosz\u00f6ld gyapj\u00fa",
    "block.minecraft.magenta_banner": "B\u00edbor z\u00e1szl\u00f3",
    "block.minecraft.magenta_bed": "B\u00edbor \u00e1gy",
    "block.minecraft.magenta_carpet": "B\u00edbor sz\u0151nyeg",
    "block.minecraft.magenta_concrete": "B\u00edbor beton",
    "block.minecraft.magenta_concrete_powder": "B\u00edbor sz\u00e1razbeton",
    "block.minecraft.magenta_glazed_terracotta": "B\u00edbor m\u00e1zas ker\u00e1mia",
    "block.minecraft.magenta_shulker_box": "B\u00edbor shulkerdoboz",
    "block.minecraft.magenta_stained_glass": "B\u00edbor festett \u00fcveg",
    "block.minecraft.magenta_stained_glass_pane": "B\u00edbor festett \u00fcveglap",
    "block.minecraft.magenta_terracotta": "B\u00edbor terrakotta",
    "block.minecraft.magenta_wool": "B\u00edbor gyapj\u00fa",
    "block.minecraft.magma_block": "Magmablokk",
    "block.minecraft.melon": "Dinnye",
    "block.minecraft.melon_stem": "Dinnyesz\u00e1r",
    "block.minecraft.mossy_cobblestone": "Moh\u00e1s z\u00fazottk\u0151",
    "block.minecraft.mossy_cobblestone_wall": "Moh\u00e1s z\u00fazottk\u0151-fal",
    "block.minecraft.mossy_stone_bricks": "Moh\u00e1s k\u0151t\u00e9gla",
    "block.minecraft.moving_piston": "Mozg\u00f3 dugatty\u00fa",
    "block.minecraft.mushroom_stem": "Gombat\u00f6nk",
    "block.minecraft.mycelium": "Mic\u00e9lium",
    "block.minecraft.nether_brick_fence": "Nethert\u00e9gla-ker\u00edt\u00e9s",
    "block.minecraft.nether_brick_slab": "Nethert\u00e9gla-lap",
    "block.minecraft.nether_brick_stairs": "Nethert\u00e9gla-l\u00e9pcs\u0151",
    "block.minecraft.nether_bricks": "Nethert\u00e9gla",
    "block.minecraft.nether_portal": "Nether-port\u00e1l",
    "block.minecraft.nether_quartz_ore": "Netherkvarc\u00e9rc",
    "block.minecraft.nether_wart": "Netherbibircs\u00f3k",
    "block.minecraft.nether_wart_block": "Netherbibircs\u00f3k-blokk",
    "block.minecraft.netherrack": "Netherrack",
    "block.minecraft.note_block": "Hangdoboz",
    "block.minecraft.oak_button": "T\u00f6lgyfa gomb",
    "block.minecraft.oak_door": "T\u00f6lgyfa ajt\u00f3",
    "block.minecraft.oak_fence": "T\u00f6lgyfa ker\u00edt\u00e9s",
    "block.minecraft.oak_fence_gate": "T\u00f6lgyfa ker\u00edt\u00e9skapu",
    "block.minecraft.oak_leaves": "T\u00f6lgylevelek",
    "block.minecraft.oak_log": "T\u00f6lgyfar\u00f6nk",
    "block.minecraft.oak_planks": "T\u00f6lgydeszka",
    "block.minecraft.oak_pressure_plate": "T\u00f6lgyfa nyom\u00f3lap",
    "block.minecraft.oak_sapling": "T\u00f6lgycsemete",
    "block.minecraft.oak_slab": "T\u00f6lgyfa lap",
    "block.minecraft.oak_stairs": "T\u00f6lgyfa l\u00e9pcs\u0151",
    "block.minecraft.oak_trapdoor": "T\u00f6lgyfa csap\u00f3ajt\u00f3",
    "block.minecraft.oak_wood": "T\u00f6lgyfablokk",
    "block.minecraft.observer": "Megfigyel\u0151",
    "block.minecraft.obsidian": "Obszidi\u00e1n",
    "block.minecraft.orange_banner": "Narancss\u00e1rga z\u00e1szl\u00f3",
    "block.minecraft.orange_bed": "Narancss\u00e1rga \u00e1gy",
    "block.minecraft.orange_carpet": "Narancss\u00e1rga sz\u0151nyeg",
    "block.minecraft.orange_concrete": "Narancss\u00e1rga beton",
    "block.minecraft.orange_concrete_powder": "Narancss\u00e1rga sz\u00e1razbeton",
    "block.minecraft.orange_glazed_terracotta": "Narancss\u00e1rga m\u00e1zas ker\u00e1mia",
    "block.minecraft.orange_shulker_box": "Narancss\u00e1rga shulkerdoboz",
    "block.minecraft.orange_stained_glass": "Narancss\u00e1rga festett \u00fcveg",
    "block.minecraft.orange_stained_glass_pane": "Narancss\u00e1rga festett \u00fcveglap",
    "block.minecraft.orange_terracotta": "Narancss\u00e1rga terrakotta",
    "block.minecraft.orange_tulip": "Narancss\u00e1rga tulip\u00e1n",
    "block.minecraft.orange_wool": "Narancss\u00e1rga gyapj\u00fa",
    "block.minecraft.oxeye_daisy": "Margar\u00e9ta",
    "block.minecraft.packed_ice": "T\u00f6m\u00f6r j\u00e9g",
    "block.minecraft.peony": "Bazsar\u00f3zsa",
    "block.minecraft.petrified_oak_slab": "Megk\u00f6v\u00fclt t\u00f6lgyfa lap",
    "block.minecraft.pink_banner": "R\u00f3zsasz\u00edn z\u00e1szl\u00f3",
    "block.minecraft.pink_bed": "R\u00f3zsasz\u00edn \u00e1gy",
    "block.minecraft.pink_carpet": "R\u00f3zsasz\u00edn sz\u0151nyeg",
    "block.minecraft.pink_concrete": "R\u00f3zsasz\u00edn beton",
    "block.minecraft.pink_concrete_powder": "R\u00f3zsasz\u00edn sz\u00e1razbeton",
    "block.minecraft.pink_glazed_terracotta": "R\u00f3zsasz\u00edn m\u00e1zas ker\u00e1mia",
    "block.minecraft.pink_shulker_box": "R\u00f3zsasz\u00edn shulkerdoboz",
    "block.minecraft.pink_stained_glass": "R\u00f3zsasz\u00edn festett \u00fcveg",
    "block.minecraft.pink_stained_glass_pane": "R\u00f3zsasz\u00edn festett \u00fcveglap",
    "block.minecraft.pink_terracotta": "R\u00f3zsasz\u00edn terrakotta",
    "block.minecraft.pink_tulip": "R\u00f3zsasz\u00edn tulip\u00e1n",
    "block.minecraft.pink_wool": "R\u00f3zsasz\u00edn gyapj\u00fa",
    "block.minecraft.piston": "Dugatty\u00fa",
    "block.minecraft.piston_head": "Dugatty\u00fafej",
    "block.minecraft.player_head": "J\u00e1t\u00e9kosfej",
    "block.minecraft.player_head.named": "%s feje",
    "block.minecraft.player_wall_head": "Fali j\u00e1t\u00e9kosfej",
    "block.minecraft.podzol": "Podzol",
    "block.minecraft.polished_andesite": "Csiszolt andezit",
    "block.minecraft.polished_diorite": "Csiszolt diorit",
    "block.minecraft.polished_granite": "Csiszolt gr\u00e1nit",
    "block.minecraft.poppy": "Pipacs",
    "block.minecraft.potatoes": "Burgony\u00e1k",
    "block.minecraft.potted_acacia_sapling": "Ak\u00e1ciacsemete cser\u00e9pben",
    "block.minecraft.potted_allium": "Hagymavir\u00e1g cser\u00e9pben",
    "block.minecraft.potted_azure_bluet": "K\u00e9kp\u00e1rna cser\u00e9pben",
    "block.minecraft.potted_birch_sapling": "Ny\u00edrfacsemete cser\u00e9pben",
    "block.minecraft.potted_blue_orchid": "K\u00e9k orchidea cser\u00e9pben",
    "block.minecraft.potted_brown_mushroom": "Barna gomba cser\u00e9pben",
    "block.minecraft.potted_cactus": "Kaktusz cser\u00e9pben",
    "block.minecraft.potted_dandelion": "Pitypang cser\u00e9pben",
    "block.minecraft.potted_dark_oak_sapling": "S\u00f6t\u00e9tt\u00f6lgycsemete cser\u00e9pben",
    "block.minecraft.potted_dead_bush": "Sz\u00e1raz k\u00f3r\u00f3 cser\u00e9pben",
    "block.minecraft.potted_fern": "P\u00e1fr\u00e1ny cser\u00e9pben",
    "block.minecraft.potted_jungle_sapling": "Dzsungelfacsemete cser\u00e9pben",
    "block.minecraft.potted_oak_sapling": "T\u00f6lgycsemete cser\u00e9pben",
    "block.minecraft.potted_orange_tulip": "Narancss\u00e1rga tulip\u00e1n cser\u00e9pben",
    "block.minecraft.potted_oxeye_daisy": "Margar\u00e9ta cser\u00e9pben",
    "block.minecraft.potted_pink_tulip": "R\u00f3zsasz\u00edn tulip\u00e1n cser\u00e9pben",
    "block.minecraft.potted_poppy": "Pipacs cser\u00e9pben",
    "block.minecraft.potted_red_mushroom": "Piros gomba cser\u00e9pben",
    "block.minecraft.potted_red_tulip": "Piros tulip\u00e1n cser\u00e9pben",
    "block.minecraft.potted_spruce_sapling": "Feny\u0151csemete cser\u00e9pben",
    "block.minecraft.potted_white_tulip": "Feh\u00e9r tulip\u00e1n cser\u00e9pben",
    "block.minecraft.powered_rail": "Elektromos s\u00edn",
    "block.minecraft.prismarine": "Prizmarin",
    "block.minecraft.prismarine_brick_slab": "Prizmarint\u00e9gla lap",
    "block.minecraft.prismarine_brick_stairs": "Prizmarint\u00e9gla l\u00e9pcs\u0151",
    "block.minecraft.prismarine_bricks": "Prizmarint\u00e9gla",
    "block.minecraft.prismarine_slab": "Prizmarinlap",
    "block.minecraft.prismarine_stairs": "Prizmarinl\u00e9pcs\u0151",
    "block.minecraft.pumpkin": "T\u00f6k",
    "block.minecraft.pumpkin_stem": "T\u00f6ksz\u00e1r",
    "block.minecraft.purple_banner": "Lila z\u00e1szl\u00f3",
    "block.minecraft.purple_bed": "Lila \u00e1gy",
    "block.minecraft.purple_carpet": "Lila sz\u0151nyeg",
    "block.minecraft.purple_concrete": "Lila beton",
    "block.minecraft.purple_concrete_powder": "Lila sz\u00e1razbeton",
    "block.minecraft.purple_glazed_terracotta": "Lila m\u00e1zas ker\u00e1mia",
    "block.minecraft.purple_shulker_box": "Lila shulkerdoboz",
    "block.minecraft.purple_stained_glass": "Lila festett \u00fcveg",
    "block.minecraft.purple_stained_glass_pane": "Lila festett \u00fcveglap",
    "block.minecraft.purple_terracotta": "Lila terrakotta",
    "block.minecraft.purple_wool": "Lila gyapj\u00fa",
    "block.minecraft.purpur_block": "Purpurblokk",
    "block.minecraft.purpur_pillar": "Purpuroszlop",
    "block.minecraft.purpur_slab": "Purpurlap",
    "block.minecraft.purpur_stairs": "Purpurl\u00e9pcs\u0151",
    "block.minecraft.quartz_block": "Kvarcblokk",
    "block.minecraft.quartz_pillar": "Kvarcoszlop",
    "block.minecraft.quartz_slab": "Kvarclap",
    "block.minecraft.quartz_stairs": "Kvarcl\u00e9pcs\u0151",
    "block.minecraft.rail": "S\u00edn",
    "block.minecraft.red_banner": "V\u00f6r\u00f6s z\u00e1szl\u00f3",
    "block.minecraft.red_bed": "V\u00f6r\u00f6s \u00e1gy",
    "block.minecraft.red_carpet": "V\u00f6r\u00f6s sz\u0151nyeg",
    "block.minecraft.red_concrete": "V\u00f6r\u00f6s beton",
    "block.minecraft.red_concrete_powder": "V\u00f6r\u00f6s sz\u00e1razbeton",
    "block.minecraft.red_glazed_terracotta": "V\u00f6r\u00f6s m\u00e1zas ker\u00e1mia",
    "block.minecraft.red_mushroom": "Piros gomba",
    "block.minecraft.red_mushroom_block": "Piros gombablokk",
    "block.minecraft.red_nether_bricks": "V\u00f6r\u00f6s nethert\u00e9gla",
    "block.minecraft.red_sand": "V\u00f6r\u00f6s homok",
    "block.minecraft.red_sandstone": "V\u00f6r\u00f6s homokk\u0151",
    "block.minecraft.red_sandstone_slab": "V\u00f6r\u00f6s homokk\u0151 lap",
    "block.minecraft.red_sandstone_stairs": "V\u00f6r\u00f6s homokk\u0151 l\u00e9pcs\u0151",
    "block.minecraft.red_shulker_box": "V\u00f6r\u00f6s shulkerdoboz",
    "block.minecraft.red_stained_glass": "V\u00f6r\u00f6s festett \u00fcveg",
    "block.minecraft.red_stained_glass_pane": "V\u00f6r\u00f6s festett \u00fcveglap",
    "block.minecraft.red_terracotta": "V\u00f6r\u00f6s terrakotta",
    "block.minecraft.red_tulip": "Piros tulip\u00e1n",
    "block.minecraft.red_wool": "V\u00f6r\u00f6s gyapj\u00fa",
    "block.minecraft.redstone_block": "Redstone-blokk",
    "block.minecraft.redstone_lamp": "Redstone-l\u00e1mpa",
    "block.minecraft.redstone_ore": "Redstone-\u00e9rc",
    "block.minecraft.redstone_torch": "Redstone-f\u00e1klya",
    "block.minecraft.redstone_wall_torch": "Fali redstone-f\u00e1klya",
    "block.minecraft.redstone_wire": "Redstone-por",
    "block.minecraft.repeater": "Redstone-jelism\u00e9tl\u0151",
    "block.minecraft.repeating_command_block": "Ism\u00e9tl\u0151 parancsblokk",
    "block.minecraft.rose_bush": "R\u00f3zsabokor",
    "block.minecraft.sand": "Homok",
    "block.minecraft.sandstone": "Homokk\u0151",
    "block.minecraft.sandstone_slab": "Homokk\u0151 lap",
    "block.minecraft.sandstone_stairs": "Homokk\u0151 l\u00e9pcs\u0151",
    "block.minecraft.sea_lantern": "Tengeri l\u00e1mp\u00e1s",
    "block.minecraft.sea_pickle": "Vil\u00e1g\u00edt\u00f3 zs\u00e1k\u00e1llat",
    "block.minecraft.seagrass": "Tengerif\u0171",
    "block.minecraft.shulker_box": "Shulkerdoboz",
    "block.minecraft.sign": "T\u00e1bla",
    "block.minecraft.skeleton_skull": "Csontv\u00e1zkoponya",
    "block.minecraft.skeleton_wall_skull": "Fali csontv\u00e1zkoponya",
    "block.minecraft.slime_block": "Ny\u00e1lkablokk",
    "block.minecraft.smooth_quartz": "Csiszolt kvarc",
    "block.minecraft.smooth_red_sandstone": "Csiszolt v\u00f6r\u00f6s homokk\u0151",
    "block.minecraft.smooth_sandstone": "Csiszolt homokk\u0151",
    "block.minecraft.smooth_stone": "Csiszolt k\u0151",
    "block.minecraft.snow": "H\u00f3",
    "block.minecraft.snow_block": "H\u00f3blokk",
    "block.minecraft.soul_sand": "L\u00e9lekhomok",
    "block.minecraft.spawner": "Id\u00e9z\u0151ketrec",
    "block.minecraft.sponge": "Szivacs",
    "block.minecraft.spruce_button": "Feny\u0151fa gomb",
    "block.minecraft.spruce_door": "Feny\u0151fa ajt\u00f3",
    "block.minecraft.spruce_fence": "Feny\u0151fa ker\u00edt\u00e9s",
    "block.minecraft.spruce_fence_gate": "Feny\u0151fa ker\u00edt\u00e9skapu",
    "block.minecraft.spruce_leaves": "Feny\u0151levelek",
    "block.minecraft.spruce_log": "Feny\u0151r\u00f6nk",
    "block.minecraft.spruce_planks": "Feny\u0151deszka",
    "block.minecraft.spruce_pressure_plate": "Feny\u0151fa nyom\u00f3lap",
    "block.minecraft.spruce_sapling": "Feny\u0151csemete",
    "block.minecraft.spruce_slab": "Feny\u0151fa lap",
    "block.minecraft.spruce_stairs": "Feny\u0151fa l\u00e9pcs\u0151",
    "block.minecraft.spruce_trapdoor": "Feny\u0151fa csap\u00f3ajt\u00f3",
    "block.minecraft.spruce_wood": "Feny\u0151blokk",
    "block.minecraft.sticky_piston": "Ragacsos dugatty\u00fa",
    "block.minecraft.stone": "K\u0151",
    "block.minecraft.stone_brick_slab": "K\u0151t\u00e9gla lap",
    "block.minecraft.stone_brick_stairs": "K\u0151t\u00e9gla-l\u00e9pcs\u0151",
    "block.minecraft.stone_bricks": "K\u0151t\u00e9gla",
    "block.minecraft.stone_button": "K\u0151gomb",
    "block.minecraft.stone_pressure_plate": "K\u0151 nyom\u00f3lap",
    "block.minecraft.stone_slab": "K\u0151lap",
    "block.minecraft.stripped_acacia_log": "K\u00e9rgezett ak\u00e1ciar\u00f6nk",
    "block.minecraft.stripped_acacia_wood": "K\u00e9rgezett ak\u00e1ciablokk",
    "block.minecraft.stripped_birch_log": "K\u00e9rgezett ny\u00edrfar\u00f6nk",
    "block.minecraft.stripped_birch_wood": "K\u00e9rgezett ny\u00edrfablokk",
    "block.minecraft.stripped_dark_oak_log": "K\u00e9rgezett s\u00f6t\u00e9tt\u00f6lgy-r\u00f6nk",
    "block.minecraft.stripped_dark_oak_wood": "K\u00e9rgezett s\u00f6t\u00e9tt\u00f6lgyblokk",
    "block.minecraft.stripped_jungle_log": "K\u00e9rgezett dzsungelfar\u00f6nk",
    "block.minecraft.stripped_jungle_wood": "K\u00e9rgezett dzsungelfablokk",
    "block.minecraft.stripped_oak_log": "K\u00e9rgezett t\u00f6lgyfar\u00f6nk",
    "block.minecraft.stripped_oak_wood": "K\u00e9rgezett t\u00f6lgyfablokk",
    "block.minecraft.stripped_spruce_log": "K\u00e9rgezett feny\u0151r\u00f6nk",
    "block.minecraft.stripped_spruce_wood": "K\u00e9rgezett feny\u0151blokk",
    "block.minecraft.structure_block": "Strukt\u00farablokk",
    "block.minecraft.structure_void": "Strukt\u00fara\u0171r",
    "block.minecraft.sugar_cane": "Cukorn\u00e1d",
    "block.minecraft.sunflower": "Napraforg\u00f3",
    "block.minecraft.tall_grass": "Magas f\u0171",
    "block.minecraft.tall_seagrass": "Magas tengerif\u0171",
    "block.minecraft.terracotta": "Terrakotta",
    "block.minecraft.three_turtle_eggs": "H\u00e1rom tekn\u0151stoj\u00e1s",
    "block.minecraft.tnt": "TNT",
    "block.minecraft.torch": "F\u00e1klya",
    "block.minecraft.trapped_chest": "Csapdal\u00e1da",
    "block.minecraft.tripwire": "Botl\u00f3dr\u00f3t",
    "block.minecraft.tripwire_hook": "Botl\u00f3dr\u00f3t-horog",
    "block.minecraft.tube_coral": "Cs\u0151korall",
    "block.minecraft.tube_coral_block": "Cs\u0151korall-blokk",
    "block.minecraft.tube_coral_fan": "Cs\u0151korall-legyez\u0151",
    "block.minecraft.tube_coral_wall_fan": "Fali cs\u0151korall-legyez\u0151",
    "block.minecraft.turtle_egg": "Tekn\u0151stoj\u00e1s",
    "block.minecraft.two_turtle_eggs": "K\u00e9t tekn\u0151stoj\u00e1s",
    "block.minecraft.vine": "Inda",
    "block.minecraft.void_air": "\u0170rb\u00e9li leveg\u0151",
    "block.minecraft.wall_banner": "Fali z\u00e1szl\u00f3",
    "block.minecraft.wall_sign": "Falit\u00e1bla",
    "block.minecraft.wall_torch": "Fali f\u00e1klya",
    "block.minecraft.water": "V\u00edz",
    "block.minecraft.wet_sponge": "Nedves szivacs",
    "block.minecraft.wheat": "B\u00fazaterm\u00e9s",
    "block.minecraft.white_banner": "Feh\u00e9r z\u00e1szl\u00f3",
    "block.minecraft.white_bed": "Feh\u00e9r \u00e1gy",
    "block.minecraft.white_carpet": "Feh\u00e9r sz\u0151nyeg",
    "block.minecraft.white_concrete": "Feh\u00e9r beton",
    "block.minecraft.white_concrete_powder": "Feh\u00e9r sz\u00e1razbeton",
    "block.minecraft.white_glazed_terracotta": "Feh\u00e9r m\u00e1zas ker\u00e1mia",
    "block.minecraft.white_shulker_box": "Feh\u00e9r shulkerdoboz",
    "block.minecraft.white_stained_glass": "Feh\u00e9r festett \u00fcveg",
    "block.minecraft.white_stained_glass_pane": "Feh\u00e9r festett \u00fcveglap",
    "block.minecraft.white_terracotta": "Feh\u00e9r terrakotta",
    "block.minecraft.white_tulip": "Feh\u00e9r tulip\u00e1n",
    "block.minecraft.white_wool": "Feh\u00e9r gyapj\u00fa",
    "block.minecraft.wither_skeleton_skull": "Withercsontv\u00e1z-koponya",
    "block.minecraft.wither_skeleton_wall_skull": "Fali withercsontv\u00e1z-koponya",
    "block.minecraft.yellow_banner": "S\u00e1rga z\u00e1szl\u00f3",
    "block.minecraft.yellow_bed": "S\u00e1rga \u00e1gy",
    "block.minecraft.yellow_carpet": "S\u00e1rga sz\u0151nyeg",
    "block.minecraft.yellow_concrete": "S\u00e1rga beton",
    "block.minecraft.yellow_concrete_powder": "S\u00e1rga sz\u00e1razbeton",
    "block.minecraft.yellow_glazed_terracotta": "S\u00e1rga m\u00e1zas ker\u00e1mia",
    "block.minecraft.yellow_shulker_box": "S\u00e1rga shulkerdoboz",
    "block.minecraft.yellow_stained_glass": "S\u00e1rga festett \u00fcveg",
    "block.minecraft.yellow_stained_glass_pane": "S\u00e1rga festett \u00fcveglap",
    "block.minecraft.yellow_terracotta": "S\u00e1rga terrakotta",
    "block.minecraft.yellow_wool": "S\u00e1rga gyapj\u00fa",
    "block.minecraft.zombie_head": "Zombifej",
    "block.minecraft.zombie_wall_head": "Fali zombifej",
    "book.byAut